(defun my-window ()
  "Draw a random rectangles with random colors in a zone, two black points
   and a circle."
  (sdl:with-init ()
    (sdl:window 640 480 :title-caption "World")
    (sdl:with-events ()
      (:quit-event () t)
      (:key-down-event ()
		       (sdl:push-quit-event))
      (:idle ()
	     (sdl:clear-display sdl:*white*)
	     (sdl:draw-box (sdl:random-rectangle 300 300)
			   :color (sdl:color :r (random 255)
					     :g (random 255)
					     :b (random 255)))
	     (sdl:draw-pixel (sdl:point :x 10 :y 10)
			     :color (sdl:color :r 0 :g 0 :b 0))
	     (sdl:draw-pixel (sdl:point :x 20 :y 20)
			     :color (sdl:color :r 0 :g 0 :b 0))
	     (sdl:draw-circle (sdl:point :x 520 :y 360)
			      60 :color (sdl:color :r (random 255)
						  :g (random 255)
						  :b (random 255)))
	     (sdl:update-display)))))
